config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    'password_resets/new'
  get    'password_resets/edit'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'likes/create'
  get    'likes/destroy'
  get    '/auth/:provider/callback',    to: 'users#facebook_login',      as: :auth_callback
  get    '/auth/failure',               to: 'users#auth_failure',        as: :auth_failure

  resources :users
  resources :account_activations, only: :edit
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:index, :create, :destroy, :show]
  resources :likes,               only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :notifications,       only: [:index]
  
  resources :users do
    member do
      # users/:id/get以下
      get :following, :followers
    end
  end
  
  resources :microposts do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :favorite_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size
  
  def favorite(user)
    likes.create(user_id: user.id)
  end
  
  def unfavorite(user)
    likes.find_by(user_id: user.id).destroy
  end
  
  def favorite?(user)
    favorite_users.include?(user)
  end
  
  def self.search(search) 
    if search
      where(['content LIKE ?', "%#{search}%"]) 
    else
      all 
    end
  end
  
  def liked_notification_by(current_user)
    notification = current_user.active_notifications.new(
      micropost_id: self.id,
      visited_id: self.user_id,
      action: "like"
    )
    notification.save if notification.valid?
  end
  
  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def index
    @microposts = Micropost.paginate(page: params[:page]).search(params[:search])
  end
  
  def show
    @microposts = Micropost.find_by(id: params[:id])
    @micropost = Micropost.find(params[:id])
    @comment = Comment.new
    @user = User.find_by(id: @micropost.user_id)
  end
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to @micropost
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<div class="col-md-4 post-content">
  <div class="microposts">
    <li id="micropost-<%= micropost.id %> ">
      
      <!--<micropost>-->
      <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
      <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
      <span class="content mp-image">
        <button type="button" class="btn"  data-toggle="modal" data-target="#micropost-<%= micropost.id %>">
          <% if micropost.picture? %>
            <%= image_tag(micropost.picture.url, :class => "post-image") %>
          <% else %>
            <%= image_tag("mp-default.png", :class => "post-image") %>
          <% end %>
        </button>
      </span>
      <div class="content mp-content">      
        <p><%= link_to(micropost.content, micropost_path(micropost)) %></p>
      </div>
      <div class="align-items-end">
        <p class="timestamp">
          Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        </p>
        <p class="mp-delete">
          <% if current_user?(micropost.user) %>
            <%= link_to "delete", micropost, method: :delete,
                                             data: { confirm: "You sure?" } %>
          <% end %>
        </p>
        <div id="likes">
          <%= render "likes/like", micropost: micropost %>
        </div>
      </div>
      
      <!-- Modal -->
      <div class="modal fade" id="micropost-<%= micropost.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <p class="modal-title" id="exampleModalCenterTitle"><%= link_to(micropost.content, micropost_path(micropost)) %></p>

              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body row">
              <div class="col-md-6">
                <span class="content mp-image">
                <button type="button" class="btn"  data-toggle="modal" data-target="#micropost-<%= micropost.id %>">
                  <% if micropost.picture? %>
                    <%= image_tag(micropost.picture.url, :class => "post-image") %>
                  <% else %>
                    <%= image_tag("mp-default.png", :class => "post-image") %>
                  <% end %>
                </button>
                </span>
              </div>          
              <div class="col-md-6">
                <div class="comment-title">
                  <p>Comments</p>
                </div>
                  <ul>
                    <% micropost.comments.each do |com| %>
                      <li class="text-left comment-list">
                        <%= com.body %>
                        by <%= link_to com.user.name, user_path(com.user.id) %>
                      </li>
                    <% end %>
                  </ul>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

    </li>
  </div>
</div>
  

app/views/microposts/index.html.erb
<% provide(:title, 'Search Posts') %>

<h1>all post</h1>

<%= will_paginate %>

<p>Micropost Search</p>
<%= form_tag microposts_path, :method => 'get' do %>
<%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

<ul class="microposts">
  <%= render @microposts %>
</ul>

<%= will_paginate %>

app/views/microposts/show.html.erb
<div class="main posts-show">
  <div id="micropost-<%= @micropost.id %>">
    <%= link_to gravatar_for(@micropost.user, size: 120), @micropost.user ,:class=>"user-name" %>
    <section class="user"><%= link_to "#{@micropost.user.name}", @micropost.user  %></section>
    <%= image_tag(@micropost.picture.url, :class => "post-image") if @micropost.picture? %>
    <p class="micropost_content">
      <%= @micropost.content %>
    </p>
    <section class="posts-show-datetime">
      <%= @microposts.created_at %>
    </section>
  </div>
  
  <div class="comment-index">
    <h3>Comments</h3>
    <% @micropost.comments.each do |comment| %>
     <section class="comments">
      <%= link_to gravatar_for(comment.user, size: 50), comment.user %>
      <p>
        <%= link_to "#{comment.user.name}" , @user %>: <%= comment.body %>
        <%= link_to "delete", micropost_comment_path(@micropost,comment), method: :delete if current_user?(comment.user) %>
      </p>
       </section>
    <% end %>
  </div>
  
  <div class="comment-form">
    <%= form_for([@micropost , @comment]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.text_area :body, placeholder: "Send comment..." %>
      </div>
      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>

  <script type="text/javascript">
    $('#micropost_picture').bind('change', function() {
      var size_in_megabytes = this.files[0].size/500/500;
      if (size_in_megabytes > 5) {
        alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
    });
  </script>
  </div> 
</div>